# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - studentperformance

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://testdockeraniket.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_7bc4a35b0c0e4138b673259fe6840de3 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9450a59c0f9240cd96f13aa2095a95dc }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: testdockeraniket.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_7bc4a35b0c0e4138b673259fe6840de3 }}/student_preformance:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'studentperformance'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2dd926db198c4a99bb1fec1c5798903c }}
        images: 'testdockeraniket.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_7bc4a35b0c0e4138b673259fe6840de3 }}/student_preformance:${{ github.sha }}'